In [1]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y) # numpy 는 numpy function 만 사용 가능 -> type 확인하기

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [8]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (112,), (38, 4), (38,))

In [11]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [14]:
log.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
log.coef_, log.intercept_

(array([[-0.41098651,  0.86047771, -2.30082014, -0.9221571 ],
        [ 0.54802376, -0.33363229, -0.14467976, -0.98769692],
        [-0.13703725, -0.52684543,  2.4454999 ,  1.90985402]]),
 array([  9.26363844,   1.68401317, -10.94765161]))

y = -0.41098651x_1 + 0.86047771x_2 + -2.30082014x_3 + -0.9221571

In [17]:
log.predict_proba(x_train[100:104])

array([[0.03344569, 0.90516931, 0.061385  ],
       [0.04240273, 0.93080489, 0.02679238],
       [0.00440551, 0.78243387, 0.21316062],
       [0.00156278, 0.5959216 , 0.40251562]])

In [18]:
log.predict(x_train[100:104])

array([1, 1, 1, 1])

In [19]:
from sklearn import metrics

In [26]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [27]:
y_pred

array([1, 1, 2, 2, 2, 0, 1, 1, 1, 0, 2, 1, 0, 0, 1, 2, 2, 0, 2, 1, 0, 2,
       2, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 1,
       0, 1, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0,
       0, 2, 0, 0, 1, 0, 1, 0, 2, 2, 0, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2,
       2, 2, 1, 0, 2, 2, 2, 1, 0, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 1,
       2, 0])

In [28]:
y_train

array([1, 1, 1, 2, 2, 0, 1, 1, 1, 0, 2, 1, 0, 0, 1, 2, 2, 0, 2, 1, 0, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 1,
       0, 1, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0,
       0, 2, 0, 0, 1, 0, 1, 0, 2, 2, 0, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2,
       2, 2, 1, 0, 2, 2, 2, 1, 0, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 1,
       2, 0])

In [31]:
print(metrics.classification_report(y_train, y_pred)) # 원래 데이터, 측정했던 데이터

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        39
           1       1.00      0.94      0.97        34
           2       0.95      1.00      0.97        39

    accuracy                           0.98       112
   macro avg       0.98      0.98      0.98       112
weighted avg       0.98      0.98      0.98       112



In [32]:
metrics.confusion_matrix(y_train, y_pred)

array([[39,  0,  0],
       [ 0, 32,  2],
       [ 0,  0, 39]], dtype=int64)